### ISSUE TITLE
Height & Width setting not working properly

### ISSUE THREAD

**Issue by ArkonM** [erossini/BlazorIconsAndFlags#1]
If just installed version 6.0.6 and I want to set different height and width for the flag
But this is not working. It sets the same value for width and height and the problem is directly in SVGFlag.cs
__builder.AddAttribute(2, "width", (object) this.Width);
__builder.AddAttribute(3, "height", (object) this.Width);

Or maybe I used it wrong but this would explain my issue

This is how I used the component (your example):
SVGFlag CountryCode="@code" FlagType="FlagType.Wide" Width="75" Height="50" 

Thanks already,
Armin

**Comment by erossini** [comment]
With the latest update, I think this issue is fixed.

**Comment by ArkonM** [comment]
No it is not fixed, i'm on version 6.0.7 now
![image](https://github.com/user-attachments/assets/8c625d07-1e1b-4eaa-ad2c-83d8202310fe)

**Comment by ArkonM** [comment]
I've made a pull request that fixes the issue: #3
